LoginAndRegister(.NetFrameworkMVC)/Controllers/ProductoController.cs
using LoginAndRegister_.NetFrameworkMVC_.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginAndRegister_.NetFrameworkMVC_.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            if (Session["Id"] != null)
            {
                using (Productos_SoftwareEntities dbModel = new Productos_SoftwareEntities())
                    return View(dbModel.Proyectos.ToList());
            }
            else
                return RedirectToAction("LoginIndex", "Login");  
        }

        [HttpGet]
        public ActionResult AddOrEdit()
        {
            if (Session["Id"] != null)
            {
                Proyecto pro = new Proyecto();
                return View(pro);
            }
            else
                return RedirectToAction("LoginIndex", "Login");
        }

        [HttpPost]
        public ActionResult AddOrEdit(Proyecto proyecto)
        {
            using (Productos_SoftwareEntities dbModel = new Productos_SoftwareEntities())
            {
                if (dbModel.Proyectos.Any(x => x.NombreProyecto == proyecto.NombreProyecto))
                {
                    ViewBag.DuplicateMessage = "El proyecto ya existe";
                    return View("AddOrEdit", proyecto);
                }

                dbModel.Proyectos.Add(proyecto);
                dbModel.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registro Exitoso";
            return View("AddOrEdit", new Proyecto());
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (Session["Id"] != null)
            {
                using (Productos_SoftwareEntities dbModel = new Productos_SoftwareEntities())
                    return View(dbModel.Proyectos.Where(x => x.IdProyecto == id).FirstOrDefault());
            }
            else
                return RedirectToAction("LoginIndex", "Login");
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (Productos_SoftwareEntities dbModel = new Productos_SoftwareEntities())
                {
                    Proyecto pro = dbModel.Proyectos.Where(x => x.IdProyecto == id).FirstOrDefault();
                    dbModel.Proyectos.Remove(pro);
                    dbModel.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ToHome()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            Session["Id"] = null;
            return RedirectToAction("LoginIndex", "Login");
        }
    }
}

LoginAndRegister(.NetFrameworkMVC)/Views/Producto/AddOrEdit.cshtml
@model LoginAndRegister_.NetFrameworkMVC_.Models.Proyecto

@{
    ViewBag.Title = "AddOrEdit";
}

<h2>AddOrEdit</h2>


@using (Html.BeginForm("AddOrEdit", "Producto", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Proyecto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdProyecto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdProyecto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdProyecto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreProyecto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreProyecto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreProyecto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoProyecto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoProyecto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoProyecto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreDesarrollador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreDesarrollador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreDesarrollador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaAsignacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaAsignacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaAsignacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEntrega, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEntrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioProyecto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioProyecto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioProyecto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-success">@ViewBag.SuccessMessage</label>
            @Html.ActionLink("Back to List", "Index");
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-danger">@ViewBag.DuplicateMessage</label>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginAndRegister(.NetFrameworkMVC)/Views/Producto/Delete.cshtml
@model LoginAndRegister_.NetFrameworkMVC_.Models.Proyecto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdProyecto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdProyecto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreProyecto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreProyecto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoProyecto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoProyecto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreDesarrollador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreDesarrollador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaAsignacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAsignacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEntrega)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEntrega)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioProyecto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioProyecto)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Producto", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LoginAndRegister(.NetFrameworkMVC)/Views/Producto/Index.cshtml
@model IEnumerable<LoginAndRegister_.NetFrameworkMVC_.Models.Proyecto>

@{
    ViewBag.Title = "Index";
}

<h2>Gestión de Productos de Software</h2>

<hr />

<h5>
    Usted como administrador tiene permiso para registrar o actualizar datos de Productos de Software.
</h5>

<p>
    @Html.ActionLink("Registrar ó Actualizar", "AddOrEdit")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdProyecto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreProyecto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoProyecto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreDesarrollador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaAsignacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaEntrega)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrecioProyecto)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdProyecto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreProyecto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoProyecto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreDesarrollador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAsignacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaEntrega)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioProyecto)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.IdProyecto })
            </td>
        </tr>
    }

</table>

<br />

<div class="row">
    <div class="col-lg-6">
        <h4>
            @Html.ActionLink("To Home", "ToHome")
        </h4>
    </div>
    <div class="col-lg-6">
        <h4>
            @Html.ActionLink("Logout", "Logout")
        </h4>
    </div>
</div>