LoginAndRegister(.NetFrameworkMVC)/Models/Empleado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAndRegister_.NetFrameworkMVC_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {
        public int Id { get; set; }
        public string Username { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string AreaTrabajo { get; set; }
    }
}

LoginAndRegister(.NetFrameworkMVC)/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoginAndRegister_.NetFrameworkMVC_.Models;

namespace LoginAndRegister_.NetFrameworkMVC_.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
        public ActionResult Index()
        {
            if (Session["Id"] != null)
            {
                using (DB_EmpleadosEntities dbModel = new DB_EmpleadosEntities())
                    return View(dbModel.Empleados.ToList());
            }
            else
                return RedirectToAction("LoginIndex", "Login");
            
        }

        [HttpGet]
        public ActionResult AddOrEdit()
        {
            if (Session["Id"] != null)
            {
                Empleado emp = new Empleado();
                return View(emp);
            }
            else
                return RedirectToAction("LoginIndex", "Login");
            
        }

        [HttpPost]
        public ActionResult AddOrEdit(Empleado empleado)
        {
            using (DB_EmpleadosEntities dbModel = new DB_EmpleadosEntities())
            {
                if (dbModel.Empleados.Any(x => x.Username == empleado.Username))
                {
                    ViewBag.DuplicateMessage = "El usuario ya existe";
                    return View("AddOrEdit", empleado);
                }

                dbModel.Empleados.Add(empleado);
                dbModel.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registro Exitoso";
            return View("AddOrEdit", new Empleado());
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (Session["Id"] != null)
            {
                using (DB_EmpleadosEntities dbModel = new DB_EmpleadosEntities())
                    return View(dbModel.Empleados.Where(x => x.Id == id).FirstOrDefault());
            }
            else
                return RedirectToAction("LoginIndex", "Login");
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (DB_EmpleadosEntities dbModel = new DB_EmpleadosEntities())
                {
                    Empleado emp = dbModel.Empleados.Where(x => x.Id == id).FirstOrDefault();
                    dbModel.Empleados.Remove(emp);
                    dbModel.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Logout()
        {
            Session["Id"] = null;
            return RedirectToAction("LoginIndex", "Login");
        }

        public ActionResult ToHome()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

LoginAndRegister(.NetFrameworkMVC)/Views/Empleado/AddOrEdit.cshtml
@model LoginAndRegister_.NetFrameworkMVC_.Models.Empleado

@{
    ViewBag.Title = "AddOrEdit";
}

<h2>Registrar o Actualizar</h2>


@using (Html.BeginForm("AddOrEdit", "Empleado", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Empleado</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrimerApellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrimerApellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrimerApellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SegundoApellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SegundoApellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SegundoApellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AreaTrabajo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AreaTrabajo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AreaTrabajo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
</div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-success">@ViewBag.SuccessMessage</label>
            @Html.ActionLink("Back to List", "Index");
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-danger">@ViewBag.DuplicateMessage</label>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LoginAndRegister(.NetFrameworkMVC)/Views/Empleado/Delete.cshtml
@model LoginAndRegister_.NetFrameworkMVC_.Models.Empleado

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimerApellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimerApellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SegundoApellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SegundoApellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AreaTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AreaTrabajo)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Empleado", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LoginAndRegister(.NetFrameworkMVC)/Views/Empleado/Index.cshtml
@model IEnumerable<LoginAndRegister_.NetFrameworkMVC_.Models.Empleado>

@{
    ViewBag.Title = "Index";
}

<h2>Gestión de Empleados</h2>

<hr/>

<h5>
    Usted como administrador tiene permiso para registrar o actualizar datos de Empleado.
</h5>

<p>
    @Html.ActionLink("Registrar ó Actualizar", "AddOrEdit")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrimerApellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SegundoApellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AreaTrabajo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Username)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Password)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nombre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PrimerApellido)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SegundoApellido)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AreaTrabajo)
    </td>
    <td>
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>

<div class="row">
    <div class="col-lg-6">
        <h4>
            @Html.ActionLink("To Home", "ToHome")
        </h4>
    </div>
    <div class="col-lg-6">
        <h4>
            @Html.ActionLink("Logout", "Logout")
        </h4>
    </div>
</div>